- hosts: kubernetes
  gather_facts: no
  roles:
    - system-config
    - docker-ce

- hosts: master
  gather_facts: no
  roles:
    - kubernetes

- hosts: node
  gather_facts: no 
  roles:
    - kubernetes