---
######## handler docker before install.
# otherwise:  manual set this before using kubernetes:
# $iptables -t nat -F
# $ip link set docker0 down
# $ip link delete docker0
# $iptables -P FORWARD ACCEPT
- name: make a dir for docker root dir
  file:
    path: /data/docker
    state: directory
    owner: root
    group: root
    mode: 0644

# # Step: copying daemon.json.
- name: copy docker daemon.josn
  template:
      dest: /etc/docker/daemon.json 
      src: templates/docker/daemon.json.jinja2
  notify:
    - restart docker
######### end handler

- name: uninstall old versions of Docker
  apt:
    name: "{{ item }}"
    state: absent
  loop:
    - docker
    - docker-engine
    - docker.io

# install using the repository
- name:  update apt packages
  apt:
    update_cache: yes

- name: install repository softs
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: add docker's official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add docker apt repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present

- name: install docker-ce
  apt:
    update_cache: yes
    name: docker-ce=17.03.2~ce-0~ubuntu-xenial
    state: present
  notify:
    - start docker

