---
- name: start docker 
  systemd:
    state: started
    name: docker
    enabled: yes

- name: reload docker
  systemd:
    state: reloaded
    name: docker

- name: restart docker
  systemd:
    state: restarted
    name: docker